openapi: 3.0.0

info:
  title: Hostname Details API
  description: Retrieve detailed information about a hostname.
  version: "v1"

servers:
  - url: https://ebbb491d-e5f0-4a3a-8992-77afbef9ba0c.mock.pstmn.io

paths:
  /hostname/{hostname}:
    get:
      operationId: getHostnameDetails
      summary: Get details about a specific hostname.
      description: Retrieve detailed information about a hostname using its identifier.
      parameters:
        - in: path
          name: hostname
          schema:
            type: string
          required: true
          description: The hostname identifier to query.
      responses:
        "200":
          description: Successful response containing hostname details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getHostnameDetailsResponse"

components:
  schemas:
    getHostnameDetailsResponse:
      type: object
      properties:
        content:
          type: string
          description: Details about the hostname.
        Device:
          type: object
          description: Information about the device associated with the hostname.
          properties:
            DeviceId:
              type: string
              description: Unique identifier of the device.
            DeviceType:
              type: string
              description: Type of the device (e.g., Laptop, Desktop).
            OperatingSystem:
              type: string
              description: Operating system installed on the device.
            LastLogin:
              type: string
              format: date-time
              description: The last login time of the device.
            Location:
              type: string
              description: Physical location of the device.
        AssetDetails:
          type: object
          description: Details about the asset.
          properties:
            AssignedUser:
              type: string
              description: Name of the user assigned to the asset.
            Department:
              type: string
              description: Department to which the asset belongs.
            PurchaseDate:
              type: string
              format: date
              description: The date the asset was purchased.
            WarrantyExpiry:
              type: string
              format: date
              description: The warranty expiry date of the asset.
            AssetTag:
              type: string
              description: Unique inventory tag for the asset.
