openapi: 3.0.0

info:
  title: Beak Dev Stream API
  description: Allows streaming of runs based on input and user-provided content.
  version: "1.0"

servers:
  - url: https://beak-dev.ilink-systems.com/api

paths:
  /bitc/runs/stream:
    post:
      operationId: postBeakDevStream
      summary: Stream runs based on user-provided content.
      description: This endpoint accepts user-provided content while other fields are preconfigured.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: array
                  description: A list containing the user-provided content.
                  items:
                    type: string
                    description: The user-provided content.
                assistant_id:
                  type: string
                  description: Hardcoded assistant ID.
                  example: "8f52cb6c-3670-4d46-8f03-ff77e7b4ac98"
                thread_id:
                  type: string
                  description: Hardcoded thread ID.
                  example: "27d4629a-d207-4d44-9372-dc8a61f307b9"
              required:
                - input
                - assistant_id
                - thread_id
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostStreamResponse"

components:
  schemas:
    PostStreamResponse:
      type: array
      description: A list of conversation messages exchanged during the session.
      items:
        type: object
        properties:
          content:
            type: string
            description: The text content of the message.
          type:
            type: string
            description: Indicates whether the message is from the user (`human`) or the AI (`ai`).
            enum: ["human", "ai"]
          id:
            type: string
            description: Unique identifier for the message.
