openapi: 3.0.0

info:
  title: Beak Dev Stream API
  description: Allows streaming of runs based on user-provided input.
  version: "1.0"

servers:
  - url: https://beak-dev.ilink-systems.com/api

paths:
  /bitc/runs/copilot/stream:
    post:
      operationId: postBeakDevStream
      summary: Stream runs based on user-provided content.
      description: |
        This endpoint processes user-provided queries in the `content` field.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: |
                    User-provided query or input. For example, asking for asset details or other 
                    relevant information to analyze.
                  example: "give me the asset details for RAS-SERVER19-Am using the Beak Dev API plugin."
              required:
                - content
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostStreamResponse"

components:
  schemas:
    PostStreamResponse:
      type: object
      description: The structured response to the user query.
      properties:
        response:
          type: string
          description: The system's response content.
